import Foundation
import PGPKit
import PGPKitGopenPGP
import Testing

@Suite(.serialized, .enabled(if: ExampleResources.isGenerationEnabled, "set PGPKIT_GENERATE_EXAMPLES=1 to regenerate"))
struct ExampleResourcesGenerator {
    private let pgp = PGP.gopenPGP()
    private let directory = ExampleResources.sourceDirectory

    private func write(_ data: Data, _ name: String) throws {
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        try data.write(to: directory.appendingPathComponent(name))
    }

    private func write(_ text: String, _ name: String) throws {
        try write(Data(text.utf8), name)
    }

    @Test
    func generateSDKExamples() async throws {
        let pair = try await pgp.keys.generateKeyPair(
            for: Fixture.identity,
            algorithm: .curve25519,
            passphrase: Fixture.passphrase
        )
        try write(await pgp.armorer.armor(pair.publicKey.data, as: .publicKey), "alice.public.asc")
        try write(await pgp.armorer.armor(pair.privateKey.data, as: .privateKey), "alice.private.asc")
        try write(pair.publicKey.data, "alice.public.gpg")
        try write(pair.privateKey.data, "alice.private.gpg")

        let message = """
        Hello from PGPKit.

        This file was encrypted with Alice's public key and can only be read with her private key
        and the passphrase "correct horse".

        """
        try write(message, "message.txt")

        let plaintext = Data(message.utf8)
        let encrypted = try await pgp.cipher.encrypt(plaintext, to: [pair.publicKey])
        try write(encrypted, "message.txt.gpg")
        try write(await pgp.armorer.armor(encrypted, as: .message), "message.txt.asc")

        let decrypted = try await pgp.cipher.decrypt(encrypted, using: pair.privateKey, passphrase: Fixture.passphrase)
        try write(decrypted, "message.decrypted.txt")

        let signature = try await pgp.signer.sign(plaintext, using: pair.privateKey, passphrase: Fixture.passphrase)
        try write(signature, "message.txt.sig")
        try write(await pgp.armorer.armor(signature, as: .signature), "message.txt.sig.asc")

        #expect(decrypted == plaintext)
    }

    @Test(.enabled(if: GPGHome.executable != nil, "gpg is not installed"))
    func generateGnuPGExamples() async throws {
        let gpg = try GPGHome()
        defer { gpg.shutdown() }
        let email = "bob@example.com"
        let generated = try gpg.runWithPassphrase(Fixture.passphrase, [
            "--quick-generate-key", "Bob GnuPG <\(email)>", "default", "default", "never",
        ])
        #expect(generated.status == 0, "\(generated.errorOutput)")
        let publicExport = try gpg.run(["--armor", "--export", email])
        let secretExport = try gpg.runWithPassphrase(Fixture.passphrase, ["--armor", "--export-secret-keys", email])
        try write(publicExport.output, "bob.public.asc")
        try write(secretExport.output, "bob.private.asc")

        let gpgPlain = workspaceFile("gnupg-plain.txt", contents: "Written and encrypted by the gpg command line.\n")
        let gpgEncrypted = directory.appendingPathComponent("gnupg-encrypted.txt.gpg")
        let encrypt = try gpg.run([
            "--trust-model", "always", "--recipient", email, "--output", gpgEncrypted.path, "--encrypt", gpgPlain.path,
        ])
        #expect(encrypt.status == 0, "\(encrypt.errorOutput)")

        let bobPublic = try await pgp.keys.importPublicKey(from: publicExport.output)
        let bobPrivate = try await pgp.keys.importPrivateKey(from: secretExport.output)
        let sdkPlain = Data("Encrypted by PGPKit for a key generated by gpg.\n".utf8)
        let sdkEncrypted = try await pgp.cipher.encrypt(sdkPlain, to: [bobPublic])
        try write(sdkEncrypted, "sdk-to-bob.txt.gpg")

        let decryptedByGPG = try gpg.runWithPassphrase(
            Fixture.passphrase,
            ["--decrypt", directory.appendingPathComponent("sdk-to-bob.txt.gpg").path]
        )
        try write(decryptedByGPG.output, "sdk-to-bob.decrypted.txt")

        let decryptedBySDK = try await pgp.cipher.decrypt(
            sdkEncrypted,
            using: bobPrivate,
            passphrase: Fixture.passphrase
        )
        #expect(decryptedByGPG.output == sdkPlain)
        #expect(decryptedBySDK == sdkPlain)
    }

    private func workspaceFile(_ name: String, contents: String) -> URL {
        let url = directory.appendingPathComponent(name)
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        try? Data(contents.utf8).write(to: url)
        return url
    }
}
